# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from Login import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminDashBoard(object):
    def setupUi(self, AdminDashBoard):
        AdminDashBoard.setObjectName("AdminDashBoard")
        AdminDashBoard.resize(914, 691)
        AdminDashBoard.setStyleSheet("bacground-color:rgb(255,255,255)")
        self.centralwidget = QtWidgets.QWidget(AdminDashBoard)
        self.centralwidget.setObjectName("centralwidget")
        AdminDashBoard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AdminDashBoard)
        self.statusbar.setObjectName("statusbar")
        AdminDashBoard.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(AdminDashBoard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 26))
        self.menubar.setStyleSheet("background-color:#44c767")
        self.menubar.setObjectName("menubar")
        self.menuDashboard = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.menuDashboard.setFont(font)
        self.menuDashboard.setStyleSheet("background-color:#44c767")
        self.menuDashboard.setObjectName("menuDashboard")
        self.menuRecords = QtWidgets.QMenu(self.menubar)
        self.menuRecords.setObjectName("menuRecords")
        AdminDashBoard.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuDashboard.menuAction())
        self.menubar.addAction(self.menuRecords.menuAction())

        self.retranslateUi(AdminDashBoard)
        QtCore.QMetaObject.connectSlotsByName(AdminDashBoard)

    def retranslateUi(self, AdminDashBoard):
        _translate = QtCore.QCoreApplication.translate
        AdminDashBoard.setWindowTitle(_translate("AdminDashBoard", "Dashboard"))
        self.menuDashboard.setTitle(_translate("AdminDashBoard", "Dashboard"))
        self.menuRecords.setTitle(_translate("AdminDashBoard", "AddEmployee"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminDashBoard = QtWidgets.QMainWindow()
    ui = Ui_AdminDashBoard()
    ui.setupUi(AdminDashBoard)
    AdminDashBoard.show()
    sys.exit(app.exec_())