# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Personnel_positionMang.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
sys.path.append(os.path.dirname(os.getcwd().replace("\\","/")))
import utils

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        '''Labels & Buttons'''
        initial_xlabel_position = 60
        initial_ylabel_position = 100
        intial_xbutton_position = 820
        intial_ybutton_position = 100
        label_x_size = 350
        label_y_size = 35
        button_x_size = 200
        button_y_size = 50
        y_margin = 100
        button_margin = button_x_size + 100
        save_button_x_position = 1500
        save_button_y_position = 1200
        save_exit_x_size = 350
        save_exit_y_size = 60
        save_exit_margin = save_exit_x_size + 100
        initial_xlineEdit_position = 350
        intial_ylineEdit_position = 100
        lineEdit_x_size = 450
        lineEdit_y_size = 50
        y_lineEdit_margin = 100

        labels = ["Full Name", "Member", "Position", "Station", "SubOffice", "Salary", "Status", "Organizational Unit", "Nature Of Assignment", "Supervisor Position"]
        for i, label in enumerate(labels):
            labelWidgets = utils.labelDrawers(self.centralwidget, initial_xlabel_position, initial_ylabel_position + i * y_margin, label_x_size, label_y_size, label)
            editbuttonWidgets = utils.pushButtonDrawers(self.centralwidget,intial_xbutton_position , intial_ybutton_position + i * y_margin ,button_x_size ,button_y_size, "Edit","")
            removebuttonWidgets = utils.pushButtonDrawers(self.centralwidget,intial_xbutton_position + button_margin , intial_ybutton_position + i * y_margin ,button_x_size ,button_y_size, "Remove","")
        self.saveButton = utils.pushButtonDrawers(self.centralwidget,save_button_x_position, save_button_y_position, save_exit_x_size, save_exit_y_size, "Save","")
        self.exitButton = utils.pushButtonDrawers(self.centralwidget,save_button_x_position + save_exit_margin, save_button_y_position, save_exit_x_size, save_exit_y_size,"Exit","")

        '''Line Edits & Combo Boxes'''
        self.fullNameLineEdit = utils.lineEditDrawers(self.centralwidget, initial_xlineEdit_position, intial_ylineEdit_position, lineEdit_x_size, lineEdit_y_size)
        self.memberComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position, intial_ylineEdit_position + 1 *y_lineEdit_margin, lineEdit_x_size, lineEdit_y_size,['Bantu'])
        self.positionComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position,intial_ylineEdit_position + 2 *y_lineEdit_margin , lineEdit_x_size, lineEdit_y_size,["Accountability" , "Transparency"])
        self.stationComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position, intial_ylineEdit_position + 3 *y_lineEdit_margin, lineEdit_x_size, lineEdit_y_size,["Addis Ababa"])
        self.subOfficeComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position, intial_ylineEdit_position + 4 *y_lineEdit_margin, lineEdit_x_size, lineEdit_y_size,["Addis Ababa"])
        self.salaryLineEdit = utils.lineEditDrawers(self.centralwidget, initial_xlineEdit_position, intial_ylineEdit_position + 5 *y_lineEdit_margin, lineEdit_x_size, lineEdit_y_size)
        self.statusComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position,intial_ylineEdit_position + 6 *y_lineEdit_margin , lineEdit_x_size, lineEdit_y_size,["Active" , "On Leave" , "Disabled"])
        self.organizationalUnitComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position,intial_ylineEdit_position + 7 *y_lineEdit_margin , lineEdit_x_size, lineEdit_y_size,["Admin","Managerial","Technical","IT"])
        self.natureOfAssignmentComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position,intial_ylineEdit_position + 8 *y_lineEdit_margin , lineEdit_x_size, lineEdit_y_size,["Managerial"])
        self.supervisorPositionComboBox = utils.comboBoxDrawers(self.centralwidget, initial_xlineEdit_position,intial_ylineEdit_position + 9 *y_lineEdit_margin ,lineEdit_x_size, lineEdit_y_size,["Accountability" , "Transparency"])
        
        MainWindow.setCentralWidget(self.centralwidget)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
