# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Personnel_viewUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
sys.path.append(os.path.dirname(os.getcwd().replace("\\","/")))
import utils


class Personel(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = utils.widgetDrawer(None,0,0,0,0)
        self.fontViewPersonnel = utils.fontSpecifier("Yu Gothic UI Semibold", 12 , True , 75)
        self.fontEmployeeCode = utils.fontSpecifier("Yu Gothic UI Semibold", 10 , False , 75)


        '''Labels'''
        self.viewPersonnelLabel = utils.labelDrawers(self.centralwidget, 20, 0, 450, 70, "View Personnel")
        self.employeeCodeLabel = utils.labelDrawers(self.centralwidget, 20, 80, 450, 40, "Employee Code")
        self.fullNameLabel = utils.labelDrawers(self.centralwidget, 20, 150, 230, 40, "Full Name")
        self.genderLabel = utils.labelDrawers(self.centralwidget , 20, 210, 230, 40 , "Gender")
        self.positionLabel = utils.labelDrawers(self.centralwidget , 20, 280, 230, 40 , "Position")
        self.salaryLabel = utils.labelDrawers(self.centralwidget , 20, 350, 230, 40 , "Salary")
        self.hireDateLabel = utils.labelDrawers(self.centralwidget , 20, 420, 230, 40 , "Hire Date")
        self.contactEndDateLabel = utils.labelDrawers(self.centralwidget , 20, 490, 450, 40 , "Contact End Date")

        '''Line Edits'''
        self.employeeCodeLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 80, 400, 50)
        self.fullNameLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 150, 400, 50)
        self.genderLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 210, 400, 50)
        self.positionLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 280, 400, 50)
        self.salaryLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 350, 400, 50)
        self.hireDateLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 420, 400, 50)
        self.contactEndDateLineEdit = utils.lineEditDrawers(self.centralwidget , 300, 490, 400, 50)

        '''Buttons'''
        self.editEmployeeCodeButton = utils.pushButtonDrawers(self.centralwidget , 720, 80, 120, 55, "Edit","")
        self.editFullNameButton = utils.pushButtonDrawers(self.centralwidget , 720, 150, 120, 55, "Edit","")
        self.editGenderButton = utils.pushButtonDrawers(self.centralwidget , 720, 210, 120, 55, "Edit","")
        self.editPositionButton = utils.pushButtonDrawers(self.centralwidget , 720, 280, 120, 55, "Edit","")
        self.editSalaryButton = utils.pushButtonDrawers(self.centralwidget , 720, 350, 120, 55, "Edit","")
        self.editHireDateButton = utils.pushButtonDrawers(self.centralwidget , 720, 420, 120, 55, "Edit","")
        self.editContactEndDateButton = utils.pushButtonDrawers(self.centralwidget , 720, 490, 120, 55, "Edit","")
        self.searchButton = utils.pushButtonDrawers(self.centralwidget , 720, 570, 120, 55, "Search","")

        '''Menu Bar'''
        self.menubar = utils.menuBarDrawer(MainWindow, 0, 0, 800, 21)
        '''Status Bar'''
        self.statusbar = utils.statusBarDrawer(MainWindow)
        
        '''Apply Options'''
        self.viewPersonnelLabel.setFont(self.fontViewPersonnel)
        self.employeeCodeLabel.setFont(self.fontEmployeeCode)
        self.fullNameLabel.setFont(self.fontEmployeeCode)
        self.genderLabel.setFont(self.fontEmployeeCode)
        self.positionLabel.setFont(self.fontEmployeeCode)
        self.salaryLabel.setFont(self.fontEmployeeCode)
        self.hireDateLabel.setFont(self.fontEmployeeCode)
        self.contactEndDateLabel.setFont(self.fontEmployeeCode)
        self.menubar.setFont(self.fontEmployeeCode)
        self.statusbar.setFont(self.fontEmployeeCode)
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setMenuBar(self.menubar)
        MainWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Personel()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
